# Generated by Django 3.2.4 on 2022-03-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='reasons',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='title',
        ),
    ]
