# Generated by Django 3.2.4 on 2022-03-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220324_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refund_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
