# Generated by Django 3.2.4 on 2022-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_received', 'order_received'), ('processed', 'processed'), ('shipped', 'shipped'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('refund_asked', 'refund_asked'), ('refunded', 'refunded')], max_length=40),
        ),
    ]
