# Generated by Django 3.2.4 on 2022-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
