# Generated by Django 3.2.4 on 2022-04-24 16:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
