# Generated by Django 3.2.4 on 2022-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
