# Generated by Django 3.2.4 on 2021-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='requested_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
