# Generated by Django 3.2.4 on 2021-07-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_passwordreset_requested_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountConfirm',
        ),
    ]
