# Generated by Django 3.2.4 on 2021-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_accountconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
