# Generated by Django 3.2.4 on 2021-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_passwordreset_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expire_time',
            field=models.DateTimeField(),
        ),
    ]
