# Generated by Django 3.2.4 on 2021-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='choice',
            field=models.CharField(choices=[('dislike', 'Dislike'), ('like', 'Like')], default='like', max_length=20),
        ),
    ]
