# Generated by Django 3.2.4 on 2021-06-29 09:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TECHNOLOGY', 'tech'), ('BOOKS', 'books'), ('APPAREL', 'apparel'), ('HOME & KITCHEN', 'h&k'), ('BEAUTY', 'beauty'), ('TOYS & GAMES', 't &g'), ('HOME ENTERTAINMENT', 'home'), ('LUGGAGE', 'luggage')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, help_text='if any', null=True, upload_to='products')),
                ('slug', models.SlugField(blank=True, max_length=400, null=True)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
